// =============== add some styles for later use ===============
let css_start_btn = `
        .start-ques {
        text-shadow: 0 0 15px #FFF, 0 0 20px #49ff18, 0 0 30px #49FF18, 0 0 40px #49FF18, 0 0 55px #49FF18, 0 0 75px #49ff18, 2px 2px 0px rgba(206,89,55,0);
        }     /* generated by https://html-css-js.com/css/generator/text-shadow/*/
        button.start-btn {
        width: 200px;
        height: 50px;
        margin-top: 20px;
        margin-left: 10px;
        margin-right: 10px;
        font-family: "Russo One", sans-serif;
        }
        .start-btn:hover{
        cursor: pointer;
        background-color: white;
        box-shadow: 0 0 15px #FFF, 0 0 20px #49ff18, 0 0 30px #49FF18, 0 0 40px #49FF18, 0 0 55px #49FF18, 0 0 75px #49ff18, 2px 2px 0px rgba(206,89,55,0);

        }
        .start-btn:focus{
        outline: none;
        background-color: gray;
        }
        .info-img{
            height: 15px;
        }`;
let style_node = document.createElement("style");
style_node.type = "text/css";
style_node.innerText = css_start_btn;
document.head.appendChild(style_node);

// event listener for checking key events for up and down!
let cur_keys = {};
document.addEventListener("keydown", function (event) {
    cur_keys[event.code] = true;
});
document.addEventListener("keyup", function (event) {
    cur_keys[event.code] = false;
});

// Driver to start the game

const driver = new Driver(document.getElementById("app"));

